name: workflow-pia-serverlist-manual

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Enter tag name for test/dev image'
        default: 'test'

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: get pia serverlist
        uses: Wandalen/wretry.action@v3
        with:
          command: |
            pia_serverlist_url='https://serverlist.piaservers.net/vpninfo/servers/v4'
            pia_port_foward_enabled_jq_filter='.regions | .[] | select(.port_forward==true) | .dns'
            pia_port_foward_enabled_result=$(curl --silent --insecure "${pia_serverlist_url}" | jq -r "${pia_port_foward_enabled_jq_filter}" || true)

            # Create empty array and append each line to it
            pia_port_foward_enabled_list=()
            while IFS= read -r line; do
                pia_port_foward_enabled_list+=("$line")
            done <<< "${pia_port_foward_enabled_result}"

            echo "[info] List of PIA endpoints that support port forwarding, generated at $(date +'%Y-%m-%d %H:%M:%S'):-"

            # loop over list of port forward enabled endpoints and echo out to console
            for i in "${pia_port_foward_enabled_list[@]}"; do
                echo "${i}"
            done
